video_path: E:/datasets/断线检测数据/安装包/yamllocal
image_size:
- 800
- 448
crop_size:
- 40
- 40
save: false
save_csv: false
video_output_path: E:/datasets/videos
save_img: true
save_img_path: C:/Users/10561/Pictures/xian
db_host: 127.0.0.1
db_port: 3306
db_user: root
db_password: xu12345678gh
db_save_day: 30
error_win: 2
correct_win: 2
BUF_SIZE: 3
HISTORY_LEN: 6
PLC_yaml: PLC_add.yaml
point_max_size: 20
medianBlur_ksize: 11
threshold_thresh: 5
kernel_ksize:
- 30
- 40
kernel_ksize2:
- 40
- 100
model_threshold: 0.5
model_path: int8_scripted.pt
recognition_fps: 0.5
